/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Course: typeof import('./src/components/Course.vue')['default']
    CoursePreview: typeof import('./src/components/CoursePreview.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Map2: typeof import('./src/components/Map2.vue')['default']
  }
}
